import "react-perfect-scrollbar/dist/css/styles.css";
// import 'swiper/swiper.min.css';
// import 'swiper/swiper.scss';
// import 'swiper/swiper-bundle.css';
import "swiper/css";
import "swiper/css/navigation";
import "../public/css/style.css";
import { createClient, configureChains, defaultChains, WagmiConfig} from 'wagmi';
import { mainnet, polygon, bsc } from 'wagmi/chains'
import { publicProvider } from 'wagmi/providers/public';
import { ChainId, ThirdwebProvider } from '@thirdweb-dev/react';
import Head from "next/head";
import ChainContext from "../context/Chain";
import { useState } from "react";

const { provider, webSocketProvider } = configureChains(
    [mainnet, polygon, bsc],
    [publicProvider()],
  )
   
  const client = createClient({
    provider,
    webSocketProvider,
  })
  
  // This is the chainId your dApp will work on.
  const activeChainId = ChainId.BinanceSmartChainMainnet;


function MyApp({ Component, pageProps }) {
    const [selectedChain, setSelectedChain] = useState(ChainId.BinanceSmartChainMainnet);
    return (
        <div>
            <ChainContext.Provider value={{ selectedChain, setSelectedChain }}>
                <ThirdwebProvider desiredChainId={selectedChain}>
                {/* <ThirdwebProvider desiredChainId={activeChainId}> */}
                    <Head>
                        <title> Defi Dashboard </title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <WagmiConfig client={client}>
                        <Component {...pageProps} />
                    </WagmiConfig>
                </ThirdwebProvider>
            </ChainContext.Provider>
        </div>
    );
}

export default MyApp;
