import "react-perfect-scrollbar/dist/css/styles.css";
// import 'swiper/swiper.min.css';
// import 'swiper/swiper.scss';
// import 'swiper/swiper-bundle.css';
import "swiper/css";
import "swiper/css/navigation";
import "../public/css/style.css";
import { createClient, configureChains, defaultChains, WagmiConfig} from 'wagmi';
import { mainnet, polygon, bsc } from 'wagmi/chains'
import { publicProvider } from 'wagmi/providers/public';
import { ChainId, ThirdwebProvider } from '@thirdweb-dev/react';
import Head from "next/head";

const { provider, webSocketProvider } = configureChains(
    [mainnet, polygon, bsc],
    [publicProvider()],
  )
   
  const client = createClient({
    provider,
    webSocketProvider,
  })
  
  // This is the chainId your dApp will work on.
  const activeChainId = ChainId.BinanceSmartChainMainnet;


function MyApp({ Component, pageProps }) {
    return (
        <div>
          <ThirdwebProvider desiredChainId={activeChainId}>
          <Head>
            <title> Defi Dashboard </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <WagmiConfig client={client}>
            <Component {...pageProps} />
          </WagmiConfig>
        </ThirdwebProvider>
      </div>
      );
}

export default MyApp;
